name: Ruby

on: [push, pull_request]

jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }} and rails ${{ matrix.rails_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rails_version: ['5.2', '6']
        ruby_version: ['2.5', '2.6']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install sqlite
      run: |
        sudo apt-get install libsqlite3-dev

    - name: Build and test with Rails ${{ matrix.rails_version }}
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
